### ISSUE TITLE
additional languages

### ISSUE THREAD

**Issue by yoshuawuyts** [liuxinyu95/AlgoXY#14]
I was wondering if you'd be open for PR's containing source code for additional languages. I'd love to contribute solutions written in JS. Thanks!

**Comment by void-elf** [comment]
I think this is a good idea, especially because it seems to me most people learn JS as their first language.
@liuxinyu95 what do you think?

**Comment by liuxinyu95** [comment]
Definitely! It will be great to have audience with different background of programming languages.
I planned to have OCaml, Scala, Erlang examples years ago. Ideally, the book can be hosted as a dynamic generated service. The user can select his/her favorite functional programming language and imperative language (Of course, it can be a uniformed one such as JS), then, he/she can generate the content, so that all the example source codes are customized.

I also realized it's necessary to provide a 'core' version, that only pseudo codes and Math formulas are include.

Anyway, it is an open book. Please feel free to make it available for more people. I really appreciate your idea!

**Comment by liuxinyu95** [comment]
Close this issue for now. I am adding examples in Java/Scala to to 'jvm' branch.
